# -*- coding: utf-8 -*-
"""Government_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_C-bKZnvIdwBoiJ7azIAXPSiD1Te1gzo
"""

import requests
from pprint import pprint
import matplotlib.pyplot as plt

def SearchProject(keyword_search='เรือดำน้ำ', year=2562, limit=20):
 
  url = 'https://opend.data.go.th/govspending/cgdcontract'

  token = 'xxxxxxxxxxxxxxx' #ต้องไปเอา API จากเว็บ data.go.th

  parameters =  {
                'api-key':token,
                'year':2562,
                'keyword':keyword_search,
                'limit':50  
                }

  r = requests.get(url, params=parameters)
  result = r.json()

  allproject =result['result']
  print('Count: ', len(allproject))  #len() คือการนับค่าใน list / Dict
  # pprint(allproject[19])

  allbudget = []
  projectname = []
  
  print('----parameter----')
  print(allproject[0].keys())

  for pj in allproject:
    print(pj['dept_name'])
    print(pj['sum_price_agree'])
    print(pj['project_name'])
    print(pj['transaction_date'])

    allbudget.append(int(pj['sum_price_agree'].replace(',','')))
    projectname.append(pj['project_name'])
    print('---------------------')

    print('**************************************')
    print('ค้นหาคำว่า: {} งบประมาณทั้งหมด: {:,d} บาท'.format(keyword_search,sum(allbudget)))
    print('**************************************')

    # plotting graph ยังไม่สมบูรณ์
    # xbar = range(len(projectname))
    # plt.bar(xbar,allbudget)
    # plt.xticks(projectname)
    # plt.show()

SearchProject('หน้ากากอนามัย',2562)